### ISSUE TITLE
Problema al actualizar la fecha de nacimiento

### ISSUE THREAD

**Issue by ncuesta** [dcesanelli/evader#1]
El dropdown del año de la fecha de nacimiento sólo muestra como opciones los años entre el 2010 y el 2020.

1. La fecha de nacimiento no puede ser futura.
2. No podrían tener clientes de más de 5 años :stuck_out_tongue_winking_eye:

Por favor, corregir el rango de años para que sea adecuado.

**Comment by dcesanelli** [comment]
Puse que pueda seleccionar desde 100 años hasta 18 años atras
